// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzpshizqkdqjdqpcdwex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cHNoaXpxa2RxamRxcGNkd2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzM0MzYsImV4cCI6MjA1OTUwOTQzNn0.0rvZFv1Dt27AqIxOCKyRMYT31y6p8yy818Oyki5QeMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);